config/routes.rb
Rails.application.routes.draw do
  resources :retail
  resources :products
   resource :carts
  root 'retail#index'

  get 'add_product/:id' => 'carts#add_product',as: :add_product
  get 'index' => 'carts#index'
  get 'destroy/:id' => 'carts#destroy',as: :delete_product

  get 'search' => 'products#search'
  get '/api' => 'products#api'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  def self.search(query)
    if query
      #TODO: Return error for empty queries
      #where('(title LIKE ?) OR (title LIKE ?) OR (content LIKE ?) OR (content LIKE ?)',
      #"%#{query}%", "%#{query.downcase}%", "%#{query}%", "%#{query.downcase}%", )

      where(['name LIKE ?',
             "%#{query.downcase}%"])
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :name, :type_of_product, :price,presence: true
	def self.search(query)
        if query
            #TODO: Return error for empty queries
            #where('(title LIKE ?) OR (title LIKE ?) OR (content LIKE ?) OR (content LIKE ?)',
                  #"%#{query}%", "%#{query.downcase}%", "%#{query}%", "%#{query.downcase}%", )

          where(['type_of_product LIKE ? OR name LIKE ?',
                  "%#{query}%", "%#{query}%"])
        end
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
require 'rest_client'
class CartsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def add




  end

  def index

    @result=Cart.all
  end

  def add_product
    #binding.pry
    #byebug
    #response=RestClient.get 'https://www.facebook.com'
    #response=RestClient.get 'https://protected-basin-4048.herokuapp.com/'
    #render json: response and return  they will send xml code or page but don't know how to get actual page.
    @name=params[:name]
    @record = Cart.search(params[:name]).first




    #flash[:error] = "plajsadke" don't know what it do. i think they are added in the session


   # @abc=Cart.find_by(:name => @name)



    if !@record.nil?
      Cart.new(name: @name,quantity: @record.quantity += 1).save
      Cart.destroy(Cart.search(params[:name]).first)
      #flash.now[:alert] = "Wrong password."
      flash[:success] = "Product's quantity is increamented in the cart" # not clear.
    else
      Cart.new(name: @name,quantity:1).save
    end
    #render xml: @record this convert @record object into xml and show it
    #render json: @record this convert @record object into json and show it
    redirect_to :action => "index"
    #render @result generating errors.
  end

  def destroy

    Cart.destroy(params[:id])
    redirect_to :action => "index"
  end

  def post_params
    params.require(:products).permit(:type_of_product, :name, :company, :price)
    params.require(:carts).permit(:name, :quantity)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController




	def index
		@product=Product.all
  end


	def show
		query = params[:id]
    @result=Product.search(query)
  end

  def new

    @result=Product.new
  end

  def destroy
    @product=Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def api
    @products = Product.all
    render json: @products
  end

  def create
    @result=Product.new(post_params)
    if @result.save
      redirect_to products_path
    else
     # render 'new'
      redirect_to new_product_path
    end
  end

  def search
    @result=Product.search(params[:q])
  end

    def post_params
      params.require(:product).permit(:type_of_product, :name, :company, :price)
    end	

end

app/controllers/retail_controller.rb
class RetailController < ApplicationController
	
	def index

	end	



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/retail_helper.rb
module RetailHelper
end

app/views/carts/add_product.html.erb
<a href="/"><%= submit_tag 'Back to Home' %></a>
<p><%= @abc.nil? %></p>
<% @record.each do |f| %>


    <h3>Name of Product: <%= f.name %></h3>
    <p>Quantity of product: <%= f.quantity  %>  </p>


<% end %>

app/views/carts/index.html.erb
<a href="/"><%= submit_tag 'Back to Home' %></a>
<h1>Items in your cart are : </h1>

<% if @result.size==0 %>
     <h3 style="color: red">no items in your cart </h3>
<% else
     @result.each do |f| %>
     <h3>Name of Product: <%= f.name %></h3>
     <p>Quantity of product: <%= f.quantity %>  </p>
     <%= link_to "Delete", delete_product_path(id: f.id), confirm: "Are you sure? Do you really want to delete it?" %>
     <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anuj</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<a href="/"><%= submit_tag 'Back to Home' %></a>
<% @product.each do |f| %>
<h3> Type of product is: <%= f.type_of_product %></h3>
<p>Company of product: <%= f.company %></p>
<p>Name of Product: <%= f.name %></p>
<p>Price of product: <%= f.price %>  </p>
   <h3> <%= link_to "Add to cart", add_product_path(id: f.id,name: f.name) %>  <%= link_to "Delete product", f, method: :delete %> </h3>

<% end %>	

app/views/products/new.html.erb
<a href="/"><%= submit_tag 'Back to Home' %></a><br/> <br/>
<%=  form_for @result do |f| %>

   * <%=  f.label :type     %>: <br/>
    <%= f.text_field :type_of_product %><br /><br/>

   * <%= f.label :Name    %>: <br/>
    <%= f.text_field :name %><br /><br/>

    <%= f.label :Company %>: <br/>
    <%= f.text_field :company %><br /><br/>

   * <%= f.label :Price   %>: <br/>
    <%= f.text_field :price %><br /><br/>
    <% #f.file_field :picture %>

    <%= f.submit %>
<% end %>

app/views/products/search.html.erb
<a href="/"><%= submit_tag 'Back to Home' %></a>
<% @result.each do |f| %>
    <h3> Type of product is: <%= f.type_of_product %></h3>
    <p>Company of product: <%= f.company %></p>
    <p>Name of Product: <%= f.name %></p>
    <p>Price of product: <%= f.price %>  </p>
    <h3><%= link_to "Add to cart", add_product_path(id: f.id,name: f.name) %> </h3>
<% end %>

app/views/products/show.html.erb
<a href="/"><%= submit_tag 'Back to Home' %></a>
  
    <% @result.each do |f| %>
        <h3> Type of product is: <%= f.type_of_product %></h3>
        <p>Company of product: <%= f.company %></p>
        <p>Name of Product: <%= f.name %></p>
        <p>Price of product: <%= f.price %>  </p>
    <h3><%= link_to "Add to cart", add_product_path(id: f.id,name: f.name) %> </h3>
    <% end %>

app/views/retail/index.html.erb
<a href="products"><%= submit_tag 'Products' %></a>
<a href="/products/new"><%= submit_tag 'Add new products' %></a>
<a href="/index"><%= submit_tag 'Cart' %></a>

</br>
</br>





<%= form_tag("/search", method: "get") do %>
<div id="text_field"><%= text_field_tag :q%></div>
<%= submit_tag 'Search' %>
<% end %>


<div id=product_image class="images">


	

 <h1><%= link_to 'Shoes',product_path('Shoes')  %>	</h1>
 <%= image_tag "shoes.jpg", :size => "500x300" %> 

 <h1><%= link_to 'Drinks',product_path('Drink') %>	</h1>
 <%= image_tag "drinks.jpg", :size => "500x300" %> 

 <h1><%= link_to 'Headphones',product_path('Headphones') %>	</h1>
 <%= image_tag "headphones.png", :size => "500x300" %> 
</div>